class ExtensionGenerator {
  static String generate({
    required double designWidth,
    required double designHeight,
    required String platform,
    String extensionName = 'AppResponsive',
  }) {
    final name =
        extensionName.trim().isEmpty ? 'AppResponsive' : extensionName.trim();
    final date = DateTime.now().toString().split('.').first;
    final platformLabel = platform == 'All' ? 'Mobile, Tablet & Web' : platform;

    return '''
// ============================================================
// Flutter Responsive Extension
// Generated by: Responsive Forge 🚀  (open-source)
// Designer Screen : ${designWidth.toInt()} × ${designHeight.toInt()} px
// Target Platform : $platformLabel
// Generated on   : $date
// ============================================================
//
// HOW TO USE:
//   context.w(100)          → responsive width
//   context.h(50)           → responsive height
//   context.sp(16)          → responsive font size
//   context.r(8)            → responsive border radius
//   context.icon(24)        → responsive icon size
//   context.pAll(16)        → EdgeInsets.all (responsive)
//   context.pH(20)          → horizontal padding
//   context.pV(12)          → vertical padding
//   context.pHV(20, 12)     → symmetric padding
//   context.pOnly(left: 8)  → custom-side padding
//   context.mAll(16)        → margin all sides
//   context.mH(20)          → horizontal margin
//   context.hSpace(20)      → vertical SizedBox
//   context.wSpace(20)      → horizontal SizedBox
//   context.vSpace16        → predefined vertical spacer
//   context.rAll(12)        → BorderRadius.circular
//   context.rTop(12)        → top-only rounded corners
//   context.isMobile        → bool
//   context.isTablet        → bool
//   context.isDesktop       → bool
//   context.responsive(mobile: x, tablet: y, desktop: z)
//   16.0.sp(context)        → num extension shorthand
//   100.0.adaptW(context)   → num extension shorthand
//
// ============================================================

import 'package:flutter/material.dart';

// ─────────────────────────────────────────────────────────────
// BuildContext Extension
// ─────────────────────────────────────────────────────────────
extension $name on BuildContext {

  // Design reference
  static const double _dW = ${designWidth.toStringAsFixed(1)};
  static const double _dH = ${designHeight.toStringAsFixed(1)};

  // ── Current screen ──────────────────────────────────────────
  double get screenWidth       => MediaQuery.of(this).size.width;
  double get screenHeight      => MediaQuery.of(this).size.height;
  bool   get isLandscape       => MediaQuery.of(this).orientation == Orientation.landscape;
  bool   get isPortrait        => MediaQuery.of(this).orientation == Orientation.portrait;
  double get statusBarHeight   => MediaQuery.of(this).padding.top;
  double get bottomBarHeight   => MediaQuery.of(this).padding.bottom;
  double get safeHeight        => screenHeight - statusBarHeight - bottomBarHeight;

  // ── Scale factors ───────────────────────────────────────────
  double get widthScale  => screenWidth  / _dW;
  double get heightScale => screenHeight / _dH;
  double get avgScale    => (widthScale + heightScale) / 2;

  // ── Dimensions ──────────────────────────────────────────────

  /// Responsive width
  double w(double val) => val * widthScale;

  /// Responsive height
  double h(double val) => val * heightScale;

  /// Responsive font size
  double sp(double val) => val * avgScale;

  /// Responsive border radius
  double r(double val) => val * avgScale;

  /// Responsive icon size
  double icon(double val) => val * avgScale;

  // ── Padding ─────────────────────────────────────────────────

  EdgeInsets pAll(double val) => EdgeInsets.all(val * avgScale);

  EdgeInsets pH(double val) =>
      EdgeInsets.symmetric(horizontal: val * widthScale);

  EdgeInsets pV(double val) =>
      EdgeInsets.symmetric(vertical: val * heightScale);

  EdgeInsets pHV(double horizontal, double vertical) => EdgeInsets.symmetric(
        horizontal: horizontal * widthScale,
        vertical:   vertical   * heightScale,
      );

  EdgeInsets pOnly({
    double left   = 0,
    double top    = 0,
    double right  = 0,
    double bottom = 0,
  }) =>
      EdgeInsets.only(
        left:   left   * widthScale,
        top:    top    * heightScale,
        right:  right  * widthScale,
        bottom: bottom * heightScale,
      );

  // ── Margin ──────────────────────────────────────────────────

  EdgeInsets mAll(double val) => EdgeInsets.all(val * avgScale);

  EdgeInsets mH(double val) =>
      EdgeInsets.symmetric(horizontal: val * widthScale);

  EdgeInsets mV(double val) =>
      EdgeInsets.symmetric(vertical: val * heightScale);

  EdgeInsets mOnly({
    double left   = 0,
    double top    = 0,
    double right  = 0,
    double bottom = 0,
  }) =>
      EdgeInsets.only(
        left:   left   * widthScale,
        top:    top    * heightScale,
        right:  right  * widthScale,
        bottom: bottom * heightScale,
      );

  // ── SizedBox Spacing ────────────────────────────────────────

  Widget hSpace(double val) => SizedBox(height: h(val));
  Widget wSpace(double val) => SizedBox(width:  w(val));

  // Predefined vertical spacers
  Widget get vSpace2  => SizedBox(height: h(2));
  Widget get vSpace4  => SizedBox(height: h(4));
  Widget get vSpace6  => SizedBox(height: h(6));
  Widget get vSpace8  => SizedBox(height: h(8));
  Widget get vSpace10 => SizedBox(height: h(10));
  Widget get vSpace12 => SizedBox(height: h(12));
  Widget get vSpace16 => SizedBox(height: h(16));
  Widget get vSpace20 => SizedBox(height: h(20));
  Widget get vSpace24 => SizedBox(height: h(24));
  Widget get vSpace32 => SizedBox(height: h(32));
  Widget get vSpace40 => SizedBox(height: h(40));
  Widget get vSpace48 => SizedBox(height: h(48));
  Widget get vSpace64 => SizedBox(height: h(64));

  // Predefined horizontal spacers
  Widget get hSpace2  => SizedBox(width: w(2));
  Widget get hSpace4  => SizedBox(width: w(4));
  Widget get hSpace6  => SizedBox(width: w(6));
  Widget get hSpace8  => SizedBox(width: w(8));
  Widget get hSpace10 => SizedBox(width: w(10));
  Widget get hSpace12 => SizedBox(width: w(12));
  Widget get hSpace16 => SizedBox(width: w(16));
  Widget get hSpace20 => SizedBox(width: w(20));
  Widget get hSpace24 => SizedBox(width: w(24));
  Widget get hSpace32 => SizedBox(width: w(32));
  Widget get hSpace40 => SizedBox(width: w(40));
  Widget get hSpace48 => SizedBox(width: w(48));
  Widget get hSpace64 => SizedBox(width: w(64));

  // ── Border Radius ────────────────────────────────────────────

  BorderRadius rAll(double val) => BorderRadius.circular(r(val));

  BorderRadius rTop(double val) => BorderRadius.only(
        topLeft:  Radius.circular(r(val)),
        topRight: Radius.circular(r(val)),
      );

  BorderRadius rBottom(double val) => BorderRadius.only(
        bottomLeft:  Radius.circular(r(val)),
        bottomRight: Radius.circular(r(val)),
      );

  BorderRadius rOnly({
    double topLeft     = 0,
    double topRight    = 0,
    double bottomLeft  = 0,
    double bottomRight = 0,
  }) =>
      BorderRadius.only(
        topLeft:     Radius.circular(r(topLeft)),
        topRight:    Radius.circular(r(topRight)),
        bottomLeft:  Radius.circular(r(bottomLeft)),
        bottomRight: Radius.circular(r(bottomRight)),
      );

  // ── Breakpoints ──────────────────────────────────────────────

  bool get isMobile  => screenWidth < 600;
  bool get isTablet  => screenWidth >= 600 && screenWidth < 1024;
  bool get isDesktop => screenWidth >= 1024;

  /// Returns a value based on current screen breakpoint.
  /// Falls back to [mobile] if the larger variant is not provided.
  T responsive<T>({required T mobile, T? tablet, T? desktop}) {
    if (isDesktop && desktop != null) return desktop;
    if (isTablet  && tablet  != null) return tablet;
    return mobile;
  }
}

// ─────────────────────────────────────────────────────────────
// num Extension — shorthand helpers
// ─────────────────────────────────────────────────────────────
extension NumResponsive on num {
  double adaptW(BuildContext ctx) => ctx.w(toDouble());
  double adaptH(BuildContext ctx) => ctx.h(toDouble());
  double sp(BuildContext ctx)     => ctx.sp(toDouble());
  double r(BuildContext ctx)      => ctx.r(toDouble());
}
''';
  }
}
